-- Seed currencies (ISO 4217 codes)
INSERT INTO public.currencies (iso_code, name, symbol, decimal_places, is_active, notes) VALUES
    ('USD', 'United States Dollar', '$', 4, true, 'Base currency for most exchange rates'),
    ('VES', 'Venezuelan Bolivarian Sovereign Bolivar', 'Bs.S', 4, true, 'Used in Facturas app; obtained from BCV via dolarapi.com'),
    ('EUR', 'Euro', '€', 4, true, NULL),
    ('MXN', 'Mexican Peso', '$', 4, true, NULL),
    ('COP', 'Colombian Peso', '$', 2, true, NULL),
    ('BRL', 'Brazilian Real', 'R$', 4, true, NULL),
    ('ARS', 'Argentine Peso', '$', 2, true, NULL),
    ('CAD', 'Canadian Dollar', 'C$', 4, true, NULL),
    ('CHF', 'Swiss Franc', 'CHF', 4, true, NULL),
    ('CNY', 'Chinese Yuan', '¥', 4, true, NULL),
    ('GBP', 'British Pound', '£', 4, true, NULL),
    ('JPY', 'Japanese Yen', '¥', 2, true, NULL),
    ('AUD', 'Australian Dollar', 'A$', 4, true, NULL),
    ('NZD', 'New Zealand Dollar', 'NZ$', 4, true, NULL),
    ('SEK', 'Swedish Krona', 'kr', 4, true, NULL),
    ('NOK', 'Norwegian Krone', 'kr', 4, true, NULL),
    ('DKK', 'Danish Krone', 'kr', 4, true, NULL),
    ('INR', 'Indian Rupee', '₹', 4, true, NULL),
    ('ZAR', 'South African Rand', 'R', 4, true, NULL),
    ('TRY', 'Turkish Lira', '₺', 4, true, NULL),
    ('PLN', 'Polish Złoty', 'zł', 4, true, NULL),
    ('HKD', 'Hong Kong Dollar', 'HK$', 4, true, NULL),
    ('SGD', 'Singapore Dollar', 'S$', 4, true, NULL),
    ('KRW', 'South Korean Won', '₩', 2, true, NULL),
    ('CZK', 'Czech Koruna', 'Kč', 4, true, NULL),
    ('HUF', 'Hungarian Forint', 'Ft', 2, true, NULL),
    ('RON', 'Romanian Leu', 'lei', 4, true, NULL),
    ('ILS', 'Israeli New Shekel', '₪', 4, true, NULL),
    ('IDR', 'Indonesian Rupiah', 'Rp', 2, true, NULL),
    ('MYR', 'Malaysian Ringgit', 'RM', 4, true, NULL),
    ('PHP', 'Philippine Peso', '₱', 4, true, NULL),
    ('THB', 'Thai Baht', '฿', 4, true, NULL),
    ('ISK', 'Icelandic Króna', 'kr', 2, true, NULL)
ON CONFLICT (iso_code) DO UPDATE SET
    name = EXCLUDED.name,
    symbol = EXCLUDED.symbol,
    decimal_places = EXCLUDED.decimal_places,
    is_active = EXCLUDED.is_active,
    notes = EXCLUDED.notes;
