-- Seed exchange rate sources
INSERT INTO public.exchange_rate_sources (key, name, url, api_key_required, supports_historical, historical_since, notes) VALUES
    ('bcv_xls',
     'BCV XLS Histórico (Tasas sistema bancario)',
     'https://www.bcv.org.ve/seccionportal/tipo-de-cambio-oficial-del-bcv',
     FALSE, TRUE, '2020-03-27',
     'Datos oficiales BCV desde archivos XLS trimestrales publicados. Disponible 2020-Q1 a hoy. Pre-2020 no publicado.'),
    ('bcv_oficial',
     'Banco Central de Venezuela (Official)',
     'https://ve.dolarapi.com/v1/dolares/oficial',
     FALSE, TRUE, '2023-01-03',
     'Official BCV rate via dolarapi.com wrapper. Historical since 2023-01-03. Replaced bcvapi.tech.'),
    ('dolarapi_paralelo',
     'Venezuela Parallel Market',
     'https://ve.dolarapi.com/v1/dolares/paralelo',
     FALSE, TRUE, '2023-01-03',
     'Parallel (black market) rate. Useful for actual market context.'),
    ('fred_dexvzus',
     'FRED DEXVZUS (Federal Reserve)',
     'https://api.stlouisfed.org/fred/series/DEXVZUS',
     TRUE, TRUE, '2018-01-01',
     'USD/VES official rate. FRED already handles VEF->VES reconversion automatically. Used for backfill 2018-2023.'),
    ('frankfurter',
     'Frankfurter.app (ECB)',
     'https://api.frankfurter.dev/v1/',
     FALSE, TRUE, '1999-01-04',
     'European Central Bank rates. Multi-currency backfill: EUR/USD, USD/MXN, USD/BRL, USD/CAD, etc.'),
    ('open_er_api',
     'Open Exchange Rates - Open Access',
     'https://open.er-api.com/v6/latest/USD',
     FALSE, FALSE, NULL,
     'Live only, no historical. Used for USD/ARS and USD/COP since no free historical source available.'),
    ('dolarapi_ars',
     'dolarapi.com Argentina',
     'https://dolarapi.com/v1/dolares/oficial',
     FALSE, FALSE, NULL,
     'Argentine peso. Live only.'),
    ('banxico',
     'Banco de Mexico',
     'https://www.banxico.org.mx/SieAPIRest/service/v1/series/SF43718',
     TRUE, TRUE, '1993-01-01',
     'USD/MXN official. Future activation.'),
    ('ecb',
     'European Central Bank',
     'https://api.frankfurter.dev/v1/latest?base=EUR',
     FALSE, TRUE, '1999-01-04',
     'For EUR rates via Frankfurter. Set up when EUR is needed.')
ON CONFLICT (key) DO UPDATE SET
    name = EXCLUDED.name,
    url = EXCLUDED.url,
    api_key_required = EXCLUDED.api_key_required,
    supports_historical = EXCLUDED.supports_historical,
    historical_since = EXCLUDED.historical_since,
    notes = EXCLUDED.notes;
